import { Platform, StyleSheet } from 'react-native';

import type { Theme } from '@/theme/palette';

export function makeHomeStyles(theme: Theme, isCompact: boolean) {
  const colors = theme.colors;

  return StyleSheet.create({
    screen: {
      backgroundColor: colors.background,
      flex: 1,
    },
    content: {
      gap: 18,
      marginHorizontal: 'auto',
      maxWidth: 860,
      paddingHorizontal: 18,
      width: '100%',
    },
    header: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 12,
    },
    headerSide: {
      alignItems: 'center',
      minWidth: 50,
    },
    brandMark: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      height: 50,
      justifyContent: 'center',
      width: 50,
    },
    headerText: {
      flex: 1,
      minWidth: 0,
    },
    title: {
      color: colors.text,
      fontSize: 26,
      fontWeight: '800',
      letterSpacing: 0,
      lineHeight: 31,
      textAlign: 'center',
    },
    headerIconButton: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 6,
      borderWidth: 1,
      height: 44,
      justifyContent: 'center',
      width: 44,
    },
    linkPanel: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 14,
      minHeight: 176,
      padding: 14,
    },
    inputShell: {
      alignItems: 'center',
      backgroundColor: colors.input,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 10,
      minHeight: 54,
      paddingHorizontal: 14,
    },
    input: {
      color: colors.text,
      flex: 1,
      fontSize: 16,
      minWidth: 0,
      paddingVertical: 12,
    },
    iconButton: {
      alignItems: 'center',
      borderRadius: 8,
      height: 36,
      justifyContent: 'center',
      width: 36,
    },
    platformGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    platformButton: {
      alignItems: 'center',
      backgroundColor: colors.input,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      height: 40,
      justifyContent: 'center',
      minWidth: 88,
      paddingHorizontal: 12,
    },
    platformButtonActive: {
      backgroundColor: colors.accentSoft,
      borderColor: colors.accent,
    },
    platformButtonText: {
      color: colors.mutedText,
      fontSize: 14,
      fontWeight: '700',
    },
    platformButtonTextActive: {
      color: colors.accent,
    },
    primaryButton: {
      alignItems: 'center',
      backgroundColor: colors.accent,
      borderRadius: 8,
      flexDirection: 'row',
      gap: 8,
      height: 52,
      justifyContent: 'center',
      paddingHorizontal: 18,
    },
    primaryButtonText: {
      color: colors.onAccent,
      fontSize: 16,
      fontWeight: '800',
    },
    disabledButton: {
      opacity: 0.48,
    },
    controlsRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    segmentShell: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 6,
      padding: 6,
    },
    segmentButton: {
      alignItems: 'center',
      borderRadius: 6,
      flexDirection: 'row',
      gap: 6,
      height: 38,
      justifyContent: 'center',
      minWidth: 82,
      paddingHorizontal: 12,
    },
    segmentButtonActive: {
      backgroundColor: colors.accent,
    },
    segmentButtonDisabled: {
      opacity: 0.42,
    },
    segmentText: {
      color: colors.mutedText,
      fontSize: 13,
      fontWeight: '800',
    },
    segmentTextActive: {
      color: colors.onAccent,
    },
    segmentTextDisabled: {
      color: colors.mutedText,
    },
    previewCard: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: Platform.OS === 'web' && !isCompact ? 'row' : 'column',
      gap: 14,
      overflow: 'hidden',
      padding: 12,
    },
    thumbnailWrap: {
      aspectRatio: 16 / 10,
      backgroundColor: colors.input,
      borderRadius: 8,
      overflow: 'hidden',
      width: Platform.OS === 'web' && !isCompact ? 250 : '100%',
    },
    thumbnail: {
      height: '100%',
      width: '100%',
    },
    thumbnailFallback: {
      alignItems: 'center',
      backgroundColor: colors.preview,
      height: '100%',
      justifyContent: 'center',
      width: '100%',
    },
    previewInfo: {
      flex: 1,
      gap: 8,
      justifyContent: 'center',
      minWidth: 0,
    },
    platformPill: {
      alignItems: 'center',
      alignSelf: 'flex-start',
      backgroundColor: colors.accentSoft,
      borderRadius: 999,
      justifyContent: 'center',
      minHeight: 28,
      paddingHorizontal: 12,
    },
    platformPillText: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: '800',
    },
    previewTitle: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '800',
      letterSpacing: 0,
      lineHeight: 25,
    },
    previewMeta: {
      color: colors.mutedText,
      fontSize: 14,
      fontWeight: '600',
    },
    notice: {
      color: colors.warning,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
    },
    unavailableText: {
      color: colors.mutedText,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
    },
    formatSection: {
      gap: 8,
      marginTop: 2,
    },
    formatLabel: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '800',
      textTransform: 'uppercase',
    },
    formatGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 8,
    },
    formatButton: {
      alignItems: 'center',
      backgroundColor: colors.input,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      height: 36,
      justifyContent: 'center',
      maxWidth: '100%',
      paddingHorizontal: 10,
    },
    formatButtonActive: {
      backgroundColor: colors.accentSoft,
      borderColor: colors.accent,
    },
    formatButtonText: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '800',
    },
    formatButtonTextActive: {
      color: colors.accent,
    },
    downloadButton: {
      alignItems: 'center',
      alignSelf: isCompact ? 'stretch' : 'flex-start',
      backgroundColor: colors.accent,
      borderRadius: 8,
      flexDirection: 'row',
      gap: 8,
      height: 46,
      justifyContent: 'center',
      marginTop: 4,
      minWidth: 180,
      paddingHorizontal: 16,
    },
    downloadButtonText: {
      color: colors.onAccent,
      flexShrink: 1,
      fontSize: 15,
      fontWeight: '800',
    },
    emptyState: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 8,
      paddingHorizontal: 20,
      paddingVertical: 28,
    },
    emptyTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '800',
      textAlign: 'center',
    },
    emptyText: {
      color: colors.mutedText,
      fontSize: 14,
      fontWeight: '600',
      lineHeight: 20,
      maxWidth: 480,
      textAlign: 'center',
    },
    noticeStrip: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSubtle,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 10,
      paddingHorizontal: 14,
      paddingVertical: 12,
    },
    noticeStripText: {
      color: colors.text,
      flex: 1,
      fontSize: 13,
      fontWeight: '700',
      lineHeight: 18,
    },
    sectionHeader: {
      alignItems: 'center',
      flexDirection: 'row',
      marginTop: 4,
    },
    sectionTitle: {
      color: colors.text,
      fontSize: 18,
      fontWeight: '800',
    },
    historyList: {
      gap: 10,
    },
    historyEmpty: {
      color: colors.mutedText,
      fontSize: 14,
      fontWeight: '600',
      paddingVertical: 10,
    },
    historyRow: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 12,
      minHeight: 64,
      padding: 12,
    },
    historyIcon: {
      alignItems: 'center',
      backgroundColor: colors.accentSoft,
      borderRadius: 8,
      height: 40,
      justifyContent: 'center',
      width: 40,
    },
    historyTextWrap: {
      flex: 1,
      minWidth: 0,
    },
    historyTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
    },
    historyMeta: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '700',
      marginTop: 2,
    },
    modalBackdrop: {
      alignItems: 'center',
      backgroundColor: colors.backdrop,
      flex: 1,
      justifyContent: 'flex-end',
      padding: 16,
    },
    actionSheet: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      gap: 12,
      maxWidth: 520,
      padding: 18,
      width: '100%',
    },
    actionTitle: {
      color: colors.text,
      fontSize: 20,
      fontWeight: '800',
    },
    actionBody: {
      color: colors.mutedText,
      fontSize: 14,
      fontWeight: '600',
      lineHeight: 20,
    },
    actionRow: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 10,
    },
    busyPanel: {
      alignItems: 'center',
      backgroundColor: colors.input,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      gap: 10,
      minHeight: 52,
      paddingHorizontal: 14,
    },
    busyText: {
      color: colors.text,
      flex: 1,
      fontSize: 14,
      fontWeight: '800',
    },
    sheetButton: {
      alignItems: 'center',
      backgroundColor: colors.accent,
      borderRadius: 8,
      flexDirection: 'row',
      flexGrow: 1,
      gap: 8,
      height: 48,
      justifyContent: 'center',
      minWidth: 140,
      paddingHorizontal: 14,
    },
    sheetButtonText: {
      color: colors.onAccent,
      fontSize: 15,
      fontWeight: '800',
    },
    sheetButtonSecondary: {
      alignItems: 'center',
      backgroundColor: colors.input,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      flexDirection: 'row',
      flexGrow: 1,
      gap: 8,
      height: 48,
      justifyContent: 'center',
      minWidth: 140,
      paddingHorizontal: 14,
    },
    sheetButtonSecondaryText: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
    },
    cancelButton: {
      alignItems: 'center',
      height: 42,
      justifyContent: 'center',
    },
    cancelButtonText: {
      color: colors.mutedText,
      fontSize: 15,
      fontWeight: '800',
    },
  });
}
