import { Platform, StyleSheet } from 'react-native';

import type { Theme } from '@/theme/palette';

export function makeMetricsStyles(theme: Theme) {
  const colors = theme.colors;

  return StyleSheet.create({
    screen: {
      backgroundColor: colors.background,
      flex: 1,
    },
    content: {
      gap: 16,
      marginHorizontal: 'auto',
      maxWidth: 880,
      paddingHorizontal: 18,
      width: '100%',
    },
    header: {
      alignItems: 'center',
      flexDirection: 'row',
      gap: 12,
    },
    iconButton: {
      alignItems: 'center',
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 8,
      borderWidth: 1,
      height: 44,
      justifyContent: 'center',
      width: 44,
    },
    headerText: {
      flex: 1,
      minWidth: 0,
    },
    title: {
      color: colors.text,
      fontSize: 28,
      fontWeight: '800',
      lineHeight: 34,
    },
    subtitle: {
      color: colors.mutedText,
      fontSize: 14,
      fontWeight: '600',
      lineHeight: 20,
      marginTop: 2,
    },
    controls: {
      alignItems: 'center',
      flexDirection: Platform.OS === 'web' ? 'row' : 'column',
      gap: 10,
      justifyContent: 'space-between',
    },
    refreshButton: {
      alignItems: 'center',
      alignSelf: Platform.OS === 'web' ? 'flex-start' : 'stretch',
      backgroundColor: colors.accent,
      borderRadius: 8,
      flexDirection: 'row',
      gap: 8,
      minHeight: 44,
      justifyContent: 'center',
      paddingHorizontal: 16,
    },
    refreshText: {
      color: colors.onAccent,
      fontSize: 14,
      fontWeight: '800',
    },
    secondaryText: {
      color: colors.mutedText,
      flex: 1,
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 18,
    },
    summaryGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      gap: 12,
    },
    statCard: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 10,
      borderWidth: 1,
      flexGrow: 1,
      flexBasis: 190,
      gap: 6,
      minWidth: 170,
      padding: 14,
    },
    statLabel: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '700',
      textTransform: 'uppercase',
    },
    statValue: {
      color: colors.text,
      fontSize: 24,
      fontWeight: '800',
    },
    statNote: {
      color: colors.mutedText,
      fontSize: 12,
      fontWeight: '600',
      lineHeight: 17,
    },
    section: {
      backgroundColor: colors.surface,
      borderColor: colors.border,
      borderRadius: 10,
      borderWidth: 1,
      gap: 12,
      padding: 14,
    },
    sectionTitle: {
      color: colors.text,
      fontSize: 16,
      fontWeight: '800',
    },
    listRow: {
      alignItems: 'center',
      borderTopColor: colors.border,
      borderTopWidth: 1,
      flexDirection: 'row',
      gap: 12,
      justifyContent: 'space-between',
      paddingVertical: 10,
    },
    listRowFirst: {
      borderTopWidth: 0,
      paddingTop: 0,
    },
    pill: {
      alignSelf: 'flex-start',
      backgroundColor: colors.accentSoft,
      borderColor: colors.accent,
      borderRadius: 999,
      borderWidth: 1,
      paddingHorizontal: 10,
      paddingVertical: 4,
    },
    pillText: {
      color: colors.accent,
      fontSize: 12,
      fontWeight: '800',
    },
    rowLabel: {
      color: colors.text,
      flex: 1,
      fontSize: 13,
      fontWeight: '700',
    },
    rowValue: {
      color: colors.mutedText,
      fontSize: 13,
      fontWeight: '800',
    },
    emptyCard: {
      alignItems: 'center',
      backgroundColor: colors.surfaceSubtle,
      borderColor: colors.border,
      borderRadius: 10,
      borderWidth: 1,
      gap: 6,
      padding: 18,
    },
    emptyTitle: {
      color: colors.text,
      fontSize: 15,
      fontWeight: '800',
    },
    emptyBody: {
      color: colors.mutedText,
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 18,
      textAlign: 'center',
    },
    errorCard: {
      backgroundColor: colors.surfaceSubtle,
      borderColor: colors.warning,
      borderRadius: 10,
      borderWidth: 1,
      padding: 14,
    },
    errorTitle: {
      color: colors.warning,
      fontSize: 15,
      fontWeight: '800',
    },
    errorBody: {
      color: colors.text,
      fontSize: 13,
      fontWeight: '600',
      lineHeight: 18,
      marginTop: 4,
    },
  });
}
